# Generated by Django 5.2.5 on 2025-08-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_initial'),
    ]

    operations = [
    ]
